name: test
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: install tools
      run: sudo apt-get -yq update && sudo apt-get -yq install clang-format clang-tools clang-19 g++ libc6-dev-i386 shellcheck
    - name: clang-format
      run: clang-format --dry-run --Werror --style llvm *.[ch]
    - name: scan-build
      run: scan-build make
    - name: shellcheck
      run: shellcheck colatrl
  build-test-deb:
    runs-on: ubuntu-latest
    environment: "release"
    container:
      image: debian:stable-slim
    steps:
    - uses: actions/checkout@v6
    - name: install deps
      run: sudo apt-get -yq update && sudo apt-get -yq install build-essential debhelper devscripts git-buildpackage clang-19 g++ libc6-dev-i386
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_commit_gpgsign: true
        git_user_signingkey: true
    - name: Check GPG Secret Keys
      run: gpg --list-secret-keys
    - name: Test GPG Signing
      run: echo "test data" | gpg --clearsign
    - name: build test
      run: sudo make install && sudo make clean
    - name: build pkg test
      run: dch -M -D noble -v "1.1-1" "test build" < /dev/null && export VER=$(dpkg-parsechangelog -Sversion | sed -E 's/\-[0-9]+$//g') && mkdir -p .pkg/colatrl-${VER} && cp -a * .pkg/colatrl-${VER} && cd .pkg/colatrl-${VER} && tar zcvf ../colatrl_${VER}.orig.tar.gz . && debuild -us -uc -S && debsign -S
  build-test:
    runs-on: ubuntu-latest
    environment: "release"
    steps:
    - uses: actions/checkout@v6
    - name: install deps
      run: sudo apt-get -yq update && sudo apt-get -yq install build-essential debhelper devscripts git-buildpackage clang-19 g++ libc6-dev-i386
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_commit_gpgsign: true
        git_user_signingkey: true
    - name: Check GPG Secret Keys
      run: gpg --list-secret-keys
    - name: Test GPG Signing
      run: echo "test data" | gpg --clearsign
    - name: build test
      run: sudo make install && sudo make clean
    - name: build pkg test
      run: dch -M -D noble -v "1.1-1" "test build" < /dev/null && export VER=$(dpkg-parsechangelog -Sversion | sed -E 's/\-[0-9]+$//g') && mkdir -p .pkg/colatrl-${VER} && cp -a * .pkg/colatrl-${VER} && cd .pkg/colatrl-${VER} && tar zcvf ../colatrl_${VER}.orig.tar.gz . && debuild -us -uc -S && debsign -S
    - name: dput test
      run: echo -e "[lp-ppa]\nfqdn = ppa.launchpad.net\nmethod = sftp\nincoming = ~anarkiwi/ubuntu/colatrl/\nlogin = anarkiwi\nallow_unsigned_uploads = 0\n" > ~/.dput.cf && ssh-keyscan ppa.launchpad.net >> ~/.ssh/known_hosts && dput -ddds lp-ppa .pkg/colatrl_*_source.changes
