name: test

on: [push, pull_request]

env:
  PKG_FILES: "BpfMap.h colatrl colatrld.c colatrld.h colatrlutil.cpp send-udp0.c Makefile LICENSE debian rpm"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: install tools
        run: sudo apt-get -yq update && sudo apt-get -yq install clang-format clang-tools clang-19 g++ libc6-dev-i386 shellcheck
      - name: clang-format
        run: clang-format --dry-run --Werror --style llvm *.[ch]
      - name: scan-build
        run: scan-build make
      - name: shellcheck
        run: shellcheck colatrl install.sh .github/scripts/gen-test-gpg-key.sh

  build-test-deb:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
      - name: install deps
        run: apt-get -yq update && apt-get -yq install build-essential debhelper devscripts git-buildpackage clang-19 g++ libc6-dev-i386 git lsb-release gnupg
      - uses: actions/checkout@v7
      - name: set safedir
        run: git config --global --add safe.directory "$(pwd)"
      - name: Generate throwaway test GPG key
        run: ./.github/scripts/gen-test-gpg-key.sh
      - name: Check GPG Secret Keys
        run: gpg --list-secret-keys
      - name: Test GPG Signing
        run: echo "test data" | gpg --clearsign
      - name: build test
        run: sudo make install && sudo make clean
      - name: build pkg test
        run: dch -M -D $(lsb_release -cs) -v "1.1-1" "test build" < /dev/null && sed -i "s/linux-tools-common/bpftool/" debian/control && export VER=$(dpkg-parsechangelog -Sversion | sed -E 's/\-[0-9]+$//g') && mkdir -p .pkg/colatrl-${VER} && cp -a ${PKG_FILES} .pkg/colatrl-${VER} && cd .pkg/colatrl-${VER} && tar zcvf ../colatrl_${VER}.orig.tar.gz . && debuild -k"$TEST_GPG_KEYID" && cp ../*deb ../..
      - name: test install
        run: apt-get install -y ./colatrl_1.1-1_amd64.deb
      - name: Upload project artifacts
        uses: actions/upload-artifact@v7
        with:
          name: colatrl_1.1-1_amd64.deb
          path: colatrl_1.1-1_amd64.deb

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: install deps
        run: sudo apt-get -yq update && sudo apt-get -yq install build-essential debhelper devscripts git-buildpackage clang-19 g++ libc6-dev-i386 gnupg
      - name: Generate throwaway test GPG key
        run: ./.github/scripts/gen-test-gpg-key.sh
      - name: Check GPG Secret Keys
        run: gpg --list-secret-keys
      - name: Test GPG Signing
        run: echo "test data" | gpg --clearsign
      - name: build test
        run: sudo make install && sudo make clean
      - name: systemd unit verify
        run: sudo systemd-analyze verify debian/colatrl.service
      - name: build pkg test
        run: dch -M -D noble -v "1.1-1" "test build" < /dev/null && export VER=$(dpkg-parsechangelog -Sversion | sed -E 's/\-[0-9]+$//g') && mkdir -p .pkg/colatrl-${VER} && cp -a ${PKG_FILES} .pkg/colatrl-${VER} && cd .pkg/colatrl-${VER} && tar zcvf ../colatrl_${VER}.orig.tar.gz . && debuild -us -uc -S && debsign -k"$TEST_GPG_KEYID" -S

  build-test-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: install deps
        run: |
          dnf -y update
          dnf -y install \
            clang gcc gcc-c++ make git \
            rpm-build rpmdevtools systemd-rpm-macros \
            gnupg2 \
            glibc-devel.i686 libgcc.i686 \
            bpftool iproute ndisc6 bind-utils

      - uses: actions/checkout@v7

      - name: set safedir
        run: git config --global --add safe.directory "$(pwd)"

      - name: Generate throwaway test GPG key
        run: ./.github/scripts/gen-test-gpg-key.sh

      - name: Check GPG Secret Keys
        run: gpg --list-secret-keys

      - name: Test GPG Signing
        run: echo "test data" | gpg --clearsign

      - name: build test
        run: make install && make clean

      - name: build pkg test
        run: |
          VER="1.1"
          RELEASE="1"
          rpmdev-setuptree
          ls -l
          cp rpm/colatrl.spec ~/rpmbuild/SPECS/colatrl.spec
          mkdir -p ~/rpmbuild/SOURCES
          tar zcvf ~/rpmbuild/SOURCES/colatrl-${VER}.tar.gz \
            --transform "s|^\.|colatrl-${VER}|" .
          rpmbuild -ba ~/rpmbuild/SPECS/colatrl.spec
          cp ~/rpmbuild/RPMS/x86_64/colatrl-${VER}-${RELEASE}*.rpm .

      - name: test install
        run: dnf -y install ./colatrl-1.1-1*.rpm

      - name: Upload project artifacts
        uses: actions/upload-artifact@v7
        with:
          name: colatrl-1.1-1.x86_64.rpm
          path: colatrl-1.1-1*.rpm
